CREATE TABLE IF NOT EXISTS consumer (
    id BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '主键ID',
    consumer_uuid VARCHAR(32) DEFAULT NULL COMMENT '用户UUID',
    phone VARCHAR(20) NOT NULL COMMENT '手机号',
    nickname VARCHAR(64) DEFAULT NULL COMMENT '用户昵称',
    avatar VARCHAR(256) DEFAULT NULL COMMENT '头像URL',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除:0-未删除 1-已删除',
    UNIQUE INDEX idx_phone (phone)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='消费者用户表';
