CREATE TABLE IF NOT EXISTS t_complaint_record (
    id BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '主键ID',
    complaint_no VARCHAR(32) NOT NULL COMMENT '投诉编号',
    product_batch_no VARCHAR(64) COMMENT '产品批次号',
    product_name VARCHAR(128) COMMENT '产品名称',
    consumer_name VARCHAR(64) COMMENT '消费者姓名',
    consumer_phone VARCHAR(20) COMMENT '消费者电话',
    complaint_type TINYINT NOT NULL COMMENT '投诉类型:1-质量投诉 2-安全投诉 3-包装投诉 4-虚假宣传 5-其他',
    complaint_title VARCHAR(256) NOT NULL COMMENT '投诉标题',
    complaint_content TEXT NOT NULL COMMENT '投诉内容',
    image_urls VARCHAR(1024) COMMENT '投诉图片URL,多个以逗号分隔',
    status TINYINT NOT NULL DEFAULT 0 COMMENT '处理状态:0-待处理 1-处理中 2-已反馈 3-已关闭',
    feedback_content TEXT COMMENT '反馈内容',
    feedback_time DATETIME COMMENT '反馈时间',
    feedback_by VARCHAR(64) COMMENT '反馈人',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除:0-未删除 1-已删除',
    INDEX idx_complaint_no (complaint_no),
    INDEX idx_product_batch_no (product_batch_no),
    INDEX idx_consumer_phone (consumer_phone),
    INDEX idx_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='消费者投诉表';
