CREATE TABLE IF NOT EXISTS scan_record (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    product_batch_no VARCHAR(64) NOT NULL,
    trace_code VARCHAR(64),
    scan_ip VARCHAR(64),
    scan_location VARCHAR(256),
    user_id VARCHAR(64),
    scan_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted TINYINT NOT NULL DEFAULT 0,
    INDEX idx_product_batch_no (product_batch_no),
    INDEX idx_trace_code (trace_code),
    INDEX idx_user_id (user_id)
);

CREATE TABLE IF NOT EXISTS t_complaint_record (
    complaint_record_id BIGINT AUTO_INCREMENT PRIMARY KEY,
    complaint_no VARCHAR(32) NOT NULL,
    trace_code VARCHAR(64),
    batch_number VARCHAR(64),
    enterprise_uuid VARCHAR(64),
    enterprise_name VARCHAR(128),
    consumer_uuid VARCHAR(64),
    complainant_name VARCHAR(64),
    phone VARCHAR(20),
    is_anonymous TINYINT DEFAULT 0,
    complaint_type TINYINT NOT NULL,
    description TEXT,
    photo_urls VARCHAR(1024),
    priority TINYINT DEFAULT 1,
    status TINYINT NOT NULL DEFAULT 1,
    handler_id VARCHAR(64),
    handler_name VARCHAR(64),
    handling_conclusion TEXT,
    handling_proof_urls VARCHAR(1024),
    submit_time TIMESTAMP NULL,
    accept_time TIMESTAMP NULL,
    close_time TIMESTAMP NULL,
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    create_by VARCHAR(64),
    update_by VARCHAR(64),
    is_deleted TINYINT NOT NULL DEFAULT 0,
    INDEX idx_complaint_no (complaint_no),
    INDEX idx_batch_number (batch_number),
    INDEX idx_phone (phone),
    INDEX idx_status (status)
);
